---
deployment:
  tasks:
    - export DEPLOYPATH=/home/raynerdc/public_html/shopnow.raynerd.com.ng
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp shop.html $DEPLOYPATH
    - /bin/cp shop.css $DEPLOYPATH
    - /bin/cp sharedfile.html $DEPLOYPATH
    - /bin/cp shared.js $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp loadProducts.js $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp checkout.css $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH
